version: '3.3'

services:
  app:
#    image: appinair/jdk11-maven
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    volumes:
      - ./:/app
    links:
      - db
    restart: always
  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
